import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import SmoothScroll from "@/components/layout/smooth-scroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full`}>
      <body className="min-h-full text-red">
        <Header />
        <SmoothScroll>
          <main>{children}</main>
        </SmoothScroll>
      </body>
    </html>
  );
}
