import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import SmoothScroll from "@/components/layout/smooth-scroll";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    // maybe we can make the loading page to shrink on the same location behind the logo?i think animate to full, initall w,h 120 then exit same as initial
  // with that willmake sure it looks like the navbar closing on page loading content?
  return (
    <html lang="en" className={`h-full`}>
      <body className="min-h-full text-red">
        <Header />

        <SmoothScroll>
          <main>{children}</main>
        </SmoothScroll>

        <Footer />
      </body>
    </html>
  );
}
