import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/header";
import SmoothScroll from "@/components/layout/smooth-scroll";
import Footer from "@/components/layout/footer";
import PageTransition from "@/components/layout/page-transition";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full`}>
      <body className="min-h-full text-red">
        <Header />

        <SmoothScroll>
          <PageTransition>
            <main>{children}</main>
          </PageTransition>
        </SmoothScroll>

        <Footer />
      </body>
    </html>
  );
}
